### ISSUE TITLE
first rough elaboration of your requirements 

### ISSUE THREAD

**Issue by kostoele** [krausma-4/car_rental_management#1]
Hey customers :grinning: !
I tried roughly to elaborate your requirements . Please let us know if some of these are not the way you imagine and if this is the case, please provide us with more information about the ones mentioned.
I was mostly uncertain about the requirements for manufacturer, invoice (as I would give this one an ID),  customer (I would give this one an ID for identification as well), model (if we have to give fixed ones or these are to be inserted when a new car is created) and also displaying all the invoices.

In the row "improved requirements" are listed all the important information we would need when we e.g. have to create a new car. By editing are mentioned only the attributes, which is possible to edit and when it comes to display/list I mentioned all the attrubutes of one object , we have to show.

|original customers' requirements| improved requirements
-- | --
|1.   organize customers |  
|1.   Create new customer |  - customer_id as an unuque number  <br>- name not empty text <br>- surname not empty text<br>- dateOfBirth in digits  form <br>- address not empty |
|2. Edit   customers | - name not empty  text <br>- surname not empty text <br> - address not empty text|
|3. Show   customer details | - customer_id <br>- name <br>- surname <br>- dateOfBirth <br> - address
|4.   Delete customers |  
|5. List   all customers | - customer_id<br>- name <br>- surname
| |  
|2.   organize cars |  
|1.   Create new car | - license   plate as an unque number <br>- manufacturer as a not empty  text    to be inserted<br>- model as not empty text to be  inserted <br>- damages as text to be inserted
|2.   Edit car Information | - manufacturer as a not empty text  to be inserted<br>- model as not empty text to be   inserted <br> - damages as text   to be inserted
|3. Show   car details | - license plate  <br>- manufacturer <br>- model <br>- damages
|4. car   delete |  
|5. List   all cars |- license plate <br>- model
|  |
|3.   organize rental contracts |  
|1.   Create a new rental contract | - invoice_id as a unuque number <br>- customer as a customer with all data   ones has<br>- car as a car with all data one car posses <br>- startDate in digits form<br>- endDate in digits form <br>- price in digits form
|2. Edit   rental contract | - startDate in digits form<br>- endDate in digits form<br>- price in digits form
|3.   Display contract |- invoice_id <br>- customer <br>- car   <br>- startDate<br>- endDate<br>- price
|4. List   all rental contract |- invoice_id <br>- customer <br>- car   <br>(where customer and car are defined only with names and models)
|  |
|4.   organise invoices |  
|1.   Create invoice |- invoice_id as a unuque number after creating a rental agreement
|2.   Display all invoices | same as displaying all rental   contracts with invoice_id, customer, car (where customer and car are defined   only with names and models)

**Comment by krausma-4** [comment]
Hey Eleonora,
for us it's important to manage our data and if you need id's for a customer, car or invoice to implement it, then you can use id's.
A manufacturer can be for example "BMW" or "Audi" and it doesnt need to be an extra entity. Same for the car model. It can be a text like "R8 V10". 

The "improved requirements" are good and you can use them to develop the domain information model.
