### ISSUE TITLE
Domain Information model

### ISSUE THREAD

**Issue by CalamariFritti** [krausma-4/car_rental_management#2]
Good evening,

we created a first draft of the Domain Information Model we are building for your app and wanted you to have a quick look at it.

One question that occured to me was: 
Is it possible that one customer can rent more than one vehicle at a time? We build the model so that it would be possible for now.

![domainInformationModel](https://user-images.githubusercontent.com/36951730/84199263-24167a00-aaa5-11ea-8cd6-2d7ad0b55bfe.png)

**Comment by krausma-4** [comment]
Looks good so far. But A customer can have more than one RentalAgreement at a time and also in generell. At the creation time of a customer it shouldn't be necessary to have already a rental agreement (0..\*). Also a car can be part of as many RentalAgreements as possible (0..\*).

**Comment by CalamariFritti** [comment]
Thanks for your feedback. We changed the multiplicities according to your answer and we think we got it right this time. 
We initially thought that a car could only be in one rental agreement at any specific time and designed it the way we did according to this assumption.

What is still a bit unclear to me: Is it possible to rent multiple cars at the same time via one agreement? If so should the multiplicity also change (to (1..*))?
 
![domainInformationModel(3)](https://user-images.githubusercontent.com/36951730/84250228-121bf200-ab0c-11ea-8a80-46731d553c96.png)

**Comment by krausma-4** [comment]
I don't think the cardinalities are about "at the same time", it's more about in generell there can be different rental agreements for the same car. But of course at the same time you cannot rent one car more than once. So we do need an invariant for this case.

It should not be possible to rent multiple cars via one agreement. The DIM displays the correct associaton.

**Comment by CalamariFritti** [comment]
Ok, i just added the invariant and will add the model to the readme.md.
