### ISSUE TITLE
design model

### ISSUE THREAD

**Issue by kostoele** [krausma-4/car_rental_management#3]
So as I understood every car or customer can have many rental agreements , but every rental agreement should and can have only one car to be rented from only one customer right?
Hope the rest okay?

![designModel](https://user-images.githubusercontent.com/44813743/84288926-21b62d80-ab42-11ea-8113-ae77ac2672c8.png)

**Comment by krausma-4** [comment]
Hey, yeah thats right. The only problem I have is that a car don't has to be at least in one rental agreement. So the cardinality should change from 1..* to *
The rest is good.

**Comment by kostoele** [comment]
Yeah right. Can you please give me rights so I can work on your repository as well? :)

**Comment by krausma-4** [comment]
Oh yes I thought I invited you already. I just added you now.

**Comment by kostoele** [comment]
Thank you :grinning:
